### ISSUE TITLE
Updated secretes do not update the private_hash_tables

### ISSUE THREAD

**Issue by do3cc** [debops/ansible-postfix#41] opened 2015-03-10 08:42 UTC
It seems a lock file is not removed at all.

**Comment by drybjed** [comment] 2015-03-10 08:49
This is currently by design. The way `debops.postfix` deals with private hash tables is this:
- Ansible sends `password_map.in` in cleartext to the server
- Makefile script creates `password_map.db` and removes `password_map.in`
Now, to prevent the never ending "changed status" of the tasks where Ansible sends the file with passwords and Makefile removes it, `password_map.lock` is created. If Ansible notices it, it doesn't send file with passwords, even if it's changed/updated.

Do you have any suggestions how to improve this process to support updating the passwords?

**Comment by Gomez** [comment] 2015-07-24 15:00
Its a little buried in the docs: 
http://docs.debops.org/en/latest/ansible/roles/ansible-postfix/docs/defaults-configuration.html#postfix-smtp-sasl-password-map

Should be presented more prominent? Any suggestions?

**Comment by drybjed** [comment] 2015-07-24 15:04
I'm working on using tagging more in roles (you will see it soon). Ansible 2.0 will bring blocks with try/except which could be used to handle this case.

**Comment by drybjed** [comment] 2017-09-09 12:03
This mechanism has been removed from the redesigned `debops.postfix`. The password tables can be implemented using provides mechanisms to manage lookup tables. I'm closing this issue as resolved.

**Closed by drybjed** 2017-09-09 12:03 UTC
